openapi: 3.0.0
info:
  title: API de Pedidos de Hamburgueria
  description: Esta API permite gerenciar pedidos em uma hamburgueria. Você pode listar, criar, atualizar e deletar pedidos.
  version: 1.0.0
paths:
  /api/pedidos:
    get:
      summary: Retorna todos os pedidos
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    cliente:
                      type: object
                      properties:
                        nome:
                          type: string
                        email:
                          type: string
                    produtos:
                      type: array
                      items:
                        type: object
                        properties:
                          produto:
                            type: string
                          quantidade:
                            type: integer
                    total:
                      type: number
                      format: float
                    data:
                      type: string
                      format: date-time
    post:
      summary: Cria um novo pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: object
                  properties:
                    nome:
                      type: string
                      example: "João Silva"
                    email:
                      type: string
                      example: "joao.silva@email.com"
                produtos:
                  type: array
                  items:
                    type: object
                    properties:
                      produto:
                        type: string
                        example: "Hambúrguer Xtreme"
                      quantidade:
                        type: integer
                        example: 2
                total:
                  type: number
                  format: float
                  example: 59.8
                data:
                  type: string
                  format: date-time
                  example: "2025-04-22T10:00:00Z"
      responses:
        '201':
          description: Pedido criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  cliente:
                    type: object
                    properties:
                      nome:
                        type: string
                      email:
                        type: string
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        produto:
                          type: string
                        quantidade:
                          type: integer
                  total:
                    type: number
                    format: float
                  data:
                    type: string
                    format: date-time
        '400':
          description: Erro ao criar pedido

  /api/pedidos/{id}:
    get:
      summary: Retorna um pedido específico pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: string
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  cliente:
                    type: object
                    properties:
                      nome:
                        type: string
                      email:
                        type: string
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        produto:
                          type: string
                        quantidade:
                          type: integer
                  total:
                    type: number
                    format: float
                  data:
                    type: string
                    format: date-time
        '404':
          description: Pedido não encontrado

    put:
      summary: Atualiza um pedido existente
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido a ser atualizado
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: object
                  properties:
                    nome:
                      type: string
                    email:
                      type: string
                produtos:
                  type: array
                  items:
                    type: object
                    properties:
                      produto:
                        type: string
                      quantidade:
                        type: integer
                total:
                  type: number
                  format: float
                data:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Pedido atualizado com sucesso
        '400':
          description: Erro ao atualizar pedido
        '404':
          description: Pedido não encontrado

    delete:
      summary: Deleta um pedido
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: string
      responses:
        '200':
          description: Pedido deletado com sucesso
        '404':
          description: Pedido não encontrado
